"""Purchase orchestration.

Business rules:
1. A ticket must contain at least one line and all quantities must be positive.
2. Repeated SKUs inside a ticket are consolidated into a single line.
3. Every SKU must exist in the catalog.
4. The whole ticket is all-or-nothing: if any line cannot be satisfied by the
   shared inventory, nothing is sold (InsufficientStock).
5. A ticket_id is generated by the service; the persistence layer writes the
   ticket and its stock deductions in one database transaction.
"""

import time
from datetime import date

from backend.app.domain.entities import (
    Product,
    PurchaseItem,
    PurchaseLine,
    PurchaseReceipt,
)
from backend.app.domain.errors import EmptyPurchase, ProductNotFound, StoreNotFound
from backend.app.domain.ports import ProductRepository, PurchaseRepository, StoreRepository
from backend.app.domain.services.inventory import plan_deductions


class PurchaseService:
    def __init__(
        self,
        products: ProductRepository,
        stores: StoreRepository,
        purchases: PurchaseRepository,
    ) -> None:
        self.products = products
        self.stores = stores
        self.purchases = purchases

    async def create_purchase(
        self, store_id: int, items: list[PurchaseItem], today: date | None = None
    ) -> PurchaseReceipt:
        if not items:
            raise EmptyPurchase()

        store = await self.stores.get(store_id)
        if store is None:
            raise StoreNotFound(store_id)

        lines = self._consolidate(items)
        products = await self._load_products(lines)

        # Pure business rule: verify feasibility against current stock before
        # touching the database. The repository re-checks atomically.
        plan_deductions({sku: p.stock for sku, p in products.items()}, lines)

        ticket_id = self._generate_ticket_id()
        fecha = today or date.today()

        # Atomic persistence: conditional stock updates + sale rows in one
        # transaction. Raises InsufficientStock on race conditions.
        await self.purchases.execute(
            store_id=store_id, ticket_id=ticket_id, fecha=fecha, lines=lines
        )

        receipt_items = [
            PurchaseLine(
                sku=item.sku,
                nombre=products[item.sku].nombre,
                cantidad=item.cantidad,
                precio_unitario=products[item.sku].precio,
                subtotal=item.cantidad * products[item.sku].precio,
            )
            for item in lines
        ]
        return PurchaseReceipt(
            ticket_id=ticket_id,
            store_id=store_id,
            fecha=fecha,
            items=receipt_items,
            total=sum(line.subtotal for line in receipt_items),
        )

    @staticmethod
    def _consolidate(items: list[PurchaseItem]) -> list[PurchaseItem]:
        merged: dict[str, int] = {}
        for item in items:
            merged[item.sku] = merged.get(item.sku, 0) + item.cantidad
        return [PurchaseItem(sku=sku, cantidad=qty) for sku, qty in merged.items()]

    async def _load_products(self, lines: list[PurchaseItem]) -> dict[str, Product]:
        products: dict[str, Product] = {}
        for item in lines:
            product = await self.products.get(item.sku)
            if product is None:
                raise ProductNotFound(item.sku)
            products[item.sku] = product
        return products

    @staticmethod
    def _generate_ticket_id() -> str:
        # Time-based id: unique enough for a POC without a sequence table.
        return f"V{int(time.time())}{int(time.time_ns() % 1000)}"
